### ISSUE TITLE
rar2fs

### ISSUE THREAD

**Issue by muddro1** [gorantornqvist/trash#2]
Hi Goran,

I have recently tried to implement your instructions for rar2fs on Freenas, but have not been able to get it to work. I cannot download the file you hosted on your website because I am getting an 502 gateway error, so I can only view it in cached mode (otherwise I would have posted there).

I am currently on freenas 11.2 and would love to know if you got it to work, and how. Thanks!

**Comment by gorantornqvist** [comment]
Hi, sorry but my server currently have hardware issues, Will have that sorted out this weekend.

I have some samba issues with rar2fs on 11.2 though. Theres a issue on rar2fs github page with more info.

I found that the easiest way to build rar2fs is to install everything needed in a jail and then use mount_unionfs in FreeNAS host /usr => /path/to/jail/usr
... and then run configure/make.

**Comment by gorantornqvist** [comment]
Should also note that rar2fs with local access works fine on 11.2, like mounting the rar2fs path in to a plex jail...which is all that I really need.

**Comment by muddro1** [comment]
Hi thanks for responding to me. Yes my main use was to use it locally, not
as samba. Also, it think building that you mention maybe a bit advanced for
me unless there were clear instructions. But at the end of the day it's
really to mount onto a jail. I saw the thread you recently sent me. I
actually commented on the bottom.

In the end I may have found an alternative method to accomplishing what I
need to do, but I may still give this a try.

The main thing was because the website was down was not able to access the
tar file you had posted.

**Comment by gorantornqvist** [comment]
Hi, my site is up again if you want to download... Den 1 feb. 2019 23:49 skrev zachmal <notifications@github.com>:Hi thanks for responding to me. Yes my main use was to use it locally, not

as samba. Also, it think building that you mention maybe a bit advanced for

me unless there were clear instructions. But at the end of the day it's

really to mount onto a jail. I saw the thread you recently sent me. I

actually commented on the bottom.



In the end I may have found an alternative method to accomplishing what I

need to do, but I may still give this a try.



The main thing was because the website was down was not able to access the

tar file you had posted.





On Fri, Feb 1, 2019, 2:12 AM Göran Törnqvist <notifications@github.com

wrote:
